### ISSUE TITLE
Missing Class ProcessOperator in VDI3628 ontology

### ISSUE THREAD

**Issue by ThorstenBigT** [hsu-aut/IndustrialStandard-ODP-VDI3682#10]
In the meta mode the process operator is included but in the owl file there is no class for it even those there are object properties refering to it

**Comment by aljoshakoecher** [comment]
Thanks for opening an issue. We are currently refactoring large parts of this ODP for a new version. One major aspect was to finally include the class ProcessOperator which was missing in previous versions. In fact, in the previous version, the class Process was used as ProcessOperator.
A big problem is the ambiguity and vagueness that VDI 3682 has. There are many concepts which are used synonymously (which is bad for a standard) and also poorly defined. Some textual definitions also deviate from the ones given in the model (VDI 3682-2).
