### ISSUE TITLE
Version information not up to date in VDI3682.owl

### ISSUE THREAD

**Issue by jelenito** [hsu-aut/IndustrialStandard-ODP-VDI3682#15]
Version information (2.0.1) does not correspond to the version / tag of the repository (3.0.0).

**Comment by aljoshakoecher** [comment]
What exactly do you mean? 
- There is a version description for 2.0.1 which -at least to me- looks like it matches the repo tag version 2.0.1
- There is a version description for 3.0.0 (the current version) which -at least to me- looks like it matches the repo tag version 3.0.0

**Comment by jelenito** [comment]
In the current version: ` <owl:versionIRI rdf:resource="http://www.hsu-ifa.de/ontologies/VDI3682/2.0.1"/>
        <owl:versionInfo>2.0.1</owl:versionInfo>`

**Comment by aljoshakoecher** [comment]
Ahhh, the versionIRI - didn't check for this. @Miguel2617, can you fix this together with #16?
