### ISSUE TITLE
VDI3682:TechnicalResource is equivalent to owl:Nothing

### ISSUE THREAD

**Issue by jelenito** [hsu-aut/IndustrialStandard-ODP-VDI3682#16]
In the description of the `TechnicalResource` there is still a restriction "equivalent To: `isAssignedTo` some `ProcessOperator`". However, the domain of `isAssignedTo` is `ProcessOperator` and the range is `TechnicalResource`. This causes an equation with class `owl:nothing` .

**Comment by aljoshakoecher** [comment]
@Miguel2617, I think this is something you overlooked :)

I think we could simply delete this restriction, right? It doesn't make sense the other way around because there should also be operators without resources.
